/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./components/Bar.vue')['default']
    CentraProjectTree: typeof import('./components/CentraProjectTree.vue')['default']
    CurseforgeIcon: typeof import('./components/CurseforgeIcon.vue')['default']
    DocsSidebar: typeof import('./components/DocsSidebar.vue')['default']
    FabricIcon: typeof import('./components/FabricIcon.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Linux: typeof import('./components/Linux.vue')['default']
    Mac: typeof import('./components/Mac.vue')['default']
    ModrinthIcon: typeof import('./components/ModrinthIcon.vue')['default']
    PackageFileIcon: typeof import('./components/PackageFileIcon.vue')['default']
    PrebuildDownloads: typeof import('./components/PrebuildDownloads.vue')['default']
    PrivacyContent: typeof import('./components/PrivacyContent.md')['default']
    QuiltIcon: typeof import('./components/QuiltIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanillaProjectTree: typeof import('./components/VanillaProjectTree.vue')['default']
    Win32: typeof import('./components/Win32.vue')['default']
    XMCLProjectTree: typeof import('./components/XMCLProjectTree.vue')['default']
    ZipFileIcon: typeof import('./components/ZipFileIcon.vue')['default']
  }
}
