// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Bar: typeof import('./components/Bar.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    Linux: typeof import('./components/Linux.vue')['default']
    Mac: typeof import('./components/Mac.vue')['default']
    PrivacyContent: typeof import('./components/PrivacyContent.md')['default']
    Win32: typeof import('./components/Win32.vue')['default']
  }
}

export { }
