name: "Deploy"
on:
  push:
    branches:
      - "docs-reload"
      - "master"
    paths:
      - .github/workflows/deploy.yaml
      - src/**
      - .vitepress/**
      - locales/**
      - public/**
      - vite.config.ts
      - vercel.json
      - package.json
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: voxelum/minecraft-launcher-core-node
          path: src/en/core
          ref: 'gh-pages'
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8.2.0
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: "Install"
        run: "pnpm i"
      - name: "Build"
        run: "pnpm run build"
        env:
          DEV: false
          PROD: true
          VITE_GITHUB_TOKEN: ${{ secrets.VITE_GITHUB_TOKEN }}
      - name: Deploy Azure
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_MUD_0911A2700 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: ".vitepress/dist" # App source code path
          api_location: "api" # Api source code path - optional
          config_file_location: "."
          skip_app_build: true
          skip_api_build: true
          ###### End of Repository/Build Configurations ######
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod ./.vitepress/dist'
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
